core/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('shop.urls', namespace='shop')),
    path('admin/', admin.site.urls),
    path('account/',include('account.urls')),    
    re_path(r'^ckeditor/', include('ckeditor_uploader.urls')),   
    
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from . import views
from .views import FeedbackListView, ContactListView

app_name = 'shop'

urlpatterns = [
    path('category/<slug:category_slug>/', views.product_list, name='product_list_by_category'),
    path('genre/<slug:genre_slug>/', views.product_list, name='product_list_by_genre'),
    path('addProduct/<str:type>', views.add_product, name = 'add_product'),
    path('search/', views.post_search, name='post_search'), 
    path('feedback/',views.feedback, name="send_feedback"),
    path('contactus/',views.contact_us , name="contact_us"),
    path('contacted_users/', ContactListView.as_view(), name="contacted_users_list"),
    path('sended_feedbacks/', FeedbackListView.as_view(), name="feedback_list"),            
    
    
    path('', views.product_list, name='product_list'), 
    path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
    path('edit/<int:product_id>/<slug:product_slug>/<str:type>', views.edit_product, name = "edit_product")
    
    
    
]

shop/models.py
from pyexpat import model
from unittest.util import _MAX_LENGTH
from django.db import models
from django.utils.text import slugify

from ckeditor_uploader.fields import RichTextUploadingField


from django.urls import reverse

class Category(models.Model):
    name = models.CharField(max_length=200, db_index=True, verbose_name="Название")
    slug = models.SlugField(max_length=200, unique=True)    
    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'
    def __str__(self):
        return self.name    
    def get_absolute_url(self):
        return reverse("shop:product_list_by_category", args=[self.slug])
  

    
class Product(models.Model):
    category = models.ForeignKey(Category, related_name='category_products', on_delete=models.CASCADE, verbose_name="Категория")
    genre = models.ManyToManyField('Genre', verbose_name="Выберите жанр", related_name='genres')
    type = models.CharField(max_length=200,blank=True, null=True)
    author = models.ForeignKey('auth.User',related_name='user_products',on_delete=models.CASCADE, verbose_name="Автор", blank=True,null=True)
    name = models.CharField(max_length=200, db_index=True, verbose_name="Название")
    slug = models.SlugField(max_length=200, unique=True)
    image = models.ImageField(upload_to = 'books/%Y/%m/%d', blank=True, verbose_name="Обложка")
    file = models.FileField(upload_to='books/pdf/%Y/%m/%d', blank = True, verbose_name="Файл Книги")
    description = models.TextField(blank=True, verbose_name="Описание")    
    content = RichTextUploadingField()
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    
    class Meta:
        ordering = ('-id',)
        index_together = (('id','slug'),)
        
        def __str__(self):
            return self.name
    
    def get_absolute_url(self):
        return reverse("shop:product_detail", args=[self.id, self.slug])
    
    def save(self,*args,**kwargs):
        i = 1
        text = slugify(self.name)        
        while Product.objects.filter(slug = text).exists() :
            i+=1            
            text = slugify(f"{text}+{i}")                           
        self.slug=slugify(text)        
        super(Product,self).save(*args,**kwargs)
  
  
class Comment(models.Model):
    product = models.ForeignKey(Product,on_delete=models.CASCADE,related_name='comments')
    name = models.CharField(max_length=80, verbose_name='Имя')
    email = models.EmailField( verbose_name='Почта')
    body = models.TextField(verbose_name='Текст')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)
    class Meta:
        ordering = ('created',)
    def __str__(self):
        return f'Comment by {self.name} on {self.product}'
        
    

class Genre(models.Model):
    name = models.CharField(max_length=200, db_index=True,verbose_name="Название")
    slug = models.SlugField(max_length=200, unique=True)     
    category = models.ForeignKey(Category, related_name='genres', on_delete=models.CASCADE)
    class Meta:
        ordering = ('name',)
        verbose_name = 'Жанр'
        verbose_name_plural = 'Жанры'
    
    def __str__(self):
        return self.name 
       
    
    
    def save(self,*args,**kwargs):
        i = 1
        text = slugify(self.name)        
        while Genre.objects.filter(slug = text).exists() :
            i+=1            
            text = slugify(f"{text}+{i}")                           
        self.slug=slugify(text)        
        super(Genre,self).save(*args,**kwargs)
        
    def get_absolute_url(self):
        return reverse("shop:product_list_by_genre", args=[self.slug])
    
    
class Feedback(models.Model):
    text = models.TextField(max_length = 1000, null=True,  blank=True, verbose_name="Сообщение")

class ContactUs(models.Model):
    name = models.CharField(max_length=200,verbose_name="Введите имю", blank=True)
    callback = models.CharField(max_length=200, verbose_name="Контакт для обратной связи")
    client_message = models.TextField(max_length=1000, verbose_name="Сообщение")

shop/forms.py
from dataclasses import field
from django import forms
from django.forms import ModelForm
from .models import Genre, Product, Comment, Feedback, ContactUs

from django.forms import Select

class ProductForm(ModelForm):  
    genre =  forms.ChoiceField(choices=[(genre.id, genre.name) for genre in Genre.objects.all()])  
    class Meta:        
        model = Product
        fields = ['name','image','author','genre','file','content']
        widgets = { 'genre': Select(attrs={'class': 'select'})}      
        
class SearchForm(forms.Form):
    query = forms.CharField()
    
class ArticleForm(ModelForm):
    # content = forms.CharField(widget=CKEditorWidget())
    class Meta:
        model = Product
        fields = ['name', 'image', 'author','content']

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')        

class FeedbackForm(forms.ModelForm):
    class Meta:
        model = Feedback
        fields=("__all__")
        
class ContactUsForm(forms.ModelForm):
    class Meta:
        model = ContactUs
        fields=("__all__")
        





# class ProductForm(forms.Form):
    
#     users = User.objects.all()
#     genres = Genre.objects.all()
#     USERS_CHOICES = ('','')
#     GENRES_CHOICES = ('','')
#     for user in users:
#         USERS_CHOICES+=("{{user.name}}","{{user.name}}")   
#     for genre in genres:
#         GENRES_CHOICES+=("{{genre.name}}","{{genre.name}}") 
#     name = forms.CharField(label='Название', max_length=100)
#     image = forms.ImageField()
#     author = forms.CharField(choices=USERS_CHOICES)
#     genre = forms.CharField(choices=GENRES_CHOICES)
#     file = forms.FileField()
#     content = forms.CharField(widget=CKEditorWidget())
    

shop/views.py
from django.shortcuts import redirect, render, get_object_or_404, redirect

from .models import ContactUs, Genre, Product, Category, Feedback
from django.contrib.auth.decorators import login_required
from django.contrib.auth.decorators import user_passes_test
from django.core.paginator import Paginator
from django.views.generic.list import ListView

from django.contrib import  messages

from django.contrib.postgres.search import SearchVector
from .forms import SearchForm, ArticleForm, ProductForm, CommentForm, FeedbackForm, ContactUsForm

def user_is_admin(user):
    return user.is_superuser



class ContactListView(ListView):
    model = ContactUs
    template_name = "shop/contacted_users.html"
    paginate_by = 10

class FeedbackListView(ListView):
    model = Feedback
    template_name = "shop/feedback_list.html"
    paginate_by = 10
    

@login_required
def contact_us(request):
    if request.method=="POST":
            form = ContactUsForm(request.POST)
            if form.is_valid():
                form = form.save() 
                messages.success(request, 'Ваше сообщение отправлено успешно')
            return redirect('shop:contact_us')
    else:
        form = ContactUsForm()
    return render(request, 'account/contact_us.html', {'form':form})
    
    
@login_required
def feedback(request):
    if request.method=="POST":
            form = FeedbackForm(request.POST)
            if form.is_valid():
                form = form.save() 
                messages.success(request, 'Ваше сообщение отправлено успешно')
            return redirect('shop:send_feedback')
    else:
        form = FeedbackForm()
    return render(request, 'account/feedback.html', {'form':form})

@login_required
@user_passes_test(user_is_admin)
def add_product(request, type):   
    print("add ga kirvotti") 
    if type == "books":
        category = Category.objects.get(slug="books")
        if request.method=="POST":
            form = ProductForm(data = request.POST, files = request.FILES)
            if form.is_valid():
                product = form.save(commit=False) 
                print(request.POST)
                genre = Genre.objects.get(id = request.POST['genre'])
                product.category = category
                product.type = "book"
                product.content = request.POST['content']   
                product.save()                            
                product.genre.add(genre)
            return redirect('account:admin_dashboard')
        else:
            form = ProductForm()
        return render(request, 'shop/admin/add.html', {'form':form})
    elif type == "articles":
        category = Category.objects.get(slug="articles")
        if request.method == "POST":
            my_form = ArticleForm(data = request.POST, files =  request.FILES)
            print(request.POST)
            if my_form.is_valid():
                product = my_form.save(commit=False)
                product.category = category
                product.content = request.POST['content']
                product.type = "article"
                product.save()
            return redirect('account:admin_dashboard')
        else:
            my_form = ArticleForm()     
        return render(request,'shop/admin/add_article.html',{'myform':my_form})
      


@login_required 
def product_list(request, category_slug = None, genre_slug = None ):    
    if request.user.is_superuser:
        return redirect("account:admin_dashboard")       
    category = None
    genre = None
    categories = Category.objects.all()
    products = Product.objects.all()
    paginator = Paginator(products, 8)     
    if category_slug:
        category = get_object_or_404(Category, slug = category_slug)
        products = products.filter(category = category)
        paginator = Paginator(products, 8)
        
    if genre_slug:
        genre = get_object_or_404(Genre, slug = genre_slug)
        products = products.filter(genre = genre)
        paginator = Paginator(products, 8)
    genres = Genre.objects.all()
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return render(request, 'account/dashboard.html', {'category':category,
                                                      'categories':categories, 
                                                      'products':products,
                                                      'page_obj': page_obj,
                                                      'genres': genres,
                                                      'genr':genre
                                                      })


@login_required
def product_detail(request, id , slug):
    product = get_object_or_404(Product, id = id , slug = slug,available=True)
    
    comments = product.comments.filter(active=True)
    
    new_comment = None
    
    if request.method == 'POST':
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.product = product
            new_comment.save()
    else:
        comment_form = CommentForm()    
    
    return render( request, 'shop/product/detail.html', {'comment_form':comment_form,
                                                         'product':product, 
                                                         'comments': comments, 
                                                         'new_comment': new_comment})

def post_search(request):
    form = SearchForm() 
    query = None
    results = []
    if 'query' in request.GET:        
        query = request.GET.get('query')
        results = Product.objects.annotate(search=SearchVector('name', 'description'),).filter(search__icontains=query)
    return render(request,'shop/product/search.html',{'form': form,'query': query,'results': results})


def edit_product(request,product_id, product_slug, type):
    product = Product.objects.get(id = product_id, slug = product_slug)
    
    if type == "book":
        if request.method == 'POST':
            product_form = ProductForm(instance=product,data=request.POST, files=request.FILES)
            if product_form.is_valid():
                product_form.save()
            return redirect("account:dashboard")
        else:
            product_form = ProductForm(instance=product) 
    elif type == "article":
        if request.method == 'POST':
            product_form = ArticleForm(instance=product,data=request.POST, files=request.FILES)
            if product_form.is_valid():
                product_form.save()
            return redirect("account:dashboard")
        else:
            product_form = ArticleForm(instance=product)
    return render(request,'shop/product/edit.html',{'product_form': product_form, 'product': product})
    

# end of the file


    

shop/templates/shop/product/detail.html
{% extends "shop/base.html" %}
{% load i18n %}
{% load static %}

{% block title %}
  {{ product.name }}
{% endblock %}

{% block content %}

  <div class="container">
    <div class="row">
      <div class="product-detail col-md-12" style="margin-top: 50px;">
        <img src="{% if product.image %}{{ product.image.url }}{% else %}
        {% static "img/no_image.png" %}{% endif %}">
        <h1>{{ product.name }}</h1>       
        {{ product.description|linebreaks }}
        {{ product.content|safe }}
        {% if product.type == "book"%}
          <div >
            <a class="btn btn-primary" role="button" href="{{product.file.url}}" download="donwload">Скачать Книгу</a>
          </div>
        {% endif %}
      </div>
      <div class="col-md-12"> 
        {% with comments.count as total_comments %}
          <h2>
            {{ total_comments }} комментарии
          </h2>
        {% endwith %}

        {% for comment in comments %}
          <div class="comment">
            <p class="info">
                Комментария от {{ comment.name }}
                {{ comment.created }}
            </p>
            {{ comment.body|linebreaks }}
          </div>
        {% empty %}
          <p>Ещё нет комментариев</p>
        {% endfor %}

        {% if new_comment %}
          <h2>Ваша комментария добавлена</h2>
          <br>
          <h2>Добавить новую комментарию</h2>
          <form action="{% url "shop:product_detail" product.id product.slug %}" method="post">
            {{ comment_form.as_p }}
            {% csrf_token %}
            <p><input type="submit" value="Добавить комментарии"></p>
          </form>
        {% else %}
          <h2>Добавить новую комментарию</h2>
          <form action="{% url "shop:product_detail" product.id product.slug %}" method="post">
            {{ comment_form.as_p }}
            {% csrf_token %}
            <p><input type="submit" value="Добавить комментарии"></p>
          </form>
        {% endif %}
      </div>
    </div>
  </div>


{% endblock %}

shop/templates/shop/product/edit.html
{% extends "shop/base.html" %}

{% block title %}Изменение{% endblock %}

{% block content %}
    {% if product.type == "book" %}
        <h1>Измените книгу</h1>
    {% elif product.type == "article" %}
        <h1>Измените статью</h1>
    {% endif %}
    <p>Вы можете изменить данные  с помощью последующей формы:</p>
    <div style="margin-top: 50px">
        <form  action = "{% url 'shop:edit_product' product.id product.slug product.type %}" enctype="multipart/form-data" method="post">
            <div class="form-class">    
                {{product_form.as_p}}
                {% csrf_token %}
                <p><input type="submit" value="Сохранить данные"></p>
            </div> 
            
        </form>
    </div>
{% endblock %}

shop/templates/shop/product/list.html
{% extends "shop/base.html" %}

{% load static %}

{% block title %}
    {% if category %}
        {{ category.name }}
    {% else %}
        Products
    {% endif %}
{% endblock %}

{% block content %}
    {% comment %} <div id="sidebar">
        <h3>Categories</h3>
        <ul>
            <li {% if not category %}class="selected"{% endif %}>
                <a href="{% url "shop:product_list" %}">All</a>
            </li>
            {% for c in categories %}
                <li {% if category.slug == c.slug %}class="selected" {% endif %}>
                    <a href="{{ c.get_absolute_url }}">
                        {{ c.name }}
                    </a>
                </li>
            {% endfor %}
        </ul>
    </div>
    <div id="main" class="product-list">
        <h1>
            {% if category %}
                {{ category.name }}
            {% else %}
                Products
            {% endif %}
        </h1>
        {% for product in products %}
            <div class="item">
                <a href="{{ product.get_absolute_url }}">
                    <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}" width="100" height="150">
                </a>
                <a href="{{ product.get_absolute_url }}">
                    {{ product.name }}
                </a>
                <br>
                ${{ product.price }}
            </div>
        {% endfor %}
    </div> {% endcomment %}
{% endblock %}

shop/templates/shop/product/search.html
{% extends "shop/base.html" %}

{% block title %}Поиск{% endblock %}

{% block content %}
    {% if query %}
        <h1>Найденные книги на данное слово: "{{ query }}"</h1>
        <h3>
            {% with results.count as total_results %}
                Найдены {{ total_results }} результатов
            {% endwith %}
        </h3>
        {% for product in results %}
            <h4>
                <a href="{{ product.get_absolute_url }}">
                    {{ product.name }}
                </a>
            </h4>
            {{ product.description }}
            <br>
            <br>
        {% empty %}
            <p>По данной слове ничего не найдено</p>
        {% endfor %}
    {% endif %}
{% endblock %}